name: Manual Sync
on:
  workflow_dispatch:  # Allow manual triggers
jobs:
  regsync:
    strategy:
      matrix:
        image:
          - registry: dhi.io
            name: static
            tag: 20250911-alpine3.22
          - registry: dhi.io
            name: golang
            tag: 1.25-alpine
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - uses: actions/checkout@v6
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Install regctl
        uses: regclient/actions/regctl-installer@main
      - name: Run regctl
        run: |
          regctl image copy \
            "${{ matrix.image.registry }}/${{ matrix.image.name }}:${{ matrix.image.tag }}" \
            "ghcr.io/mathieu-benoit/${{ matrix.image.name }}:${{ matrix.image.tag }}" \
            --force-recursive